[package]
name = "cloudlog-adifwatch"
version = "0.0.14"
authors = ["Mikael Voss <mvs@nya.yt>"]
edition = "2021"

description = "Automatic upload of ADIF log to Cloudlog"
readme = "README.md"
repository = "https://github.com/illdefined/cloudlog-adifwatch"

license = "MirOS"

keywords = ["amateur-radio", "adif"]
categories = ["command-line-utilities"]

[dependencies]
lazy_static = "1.4"
notify = "4.0"
regex = "1.6"
ureq = { version = "2.5", features = ["json"] }
url = "2.2"

[profile.release]
lto = "thin"
