name: Rust Vulnerability Audit

on:
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  schedule:
    - cron: '0 0 * * MON'
  workflow_dispatch:

jobs:
  audit:
    name: Rust Audit
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macos-15
          - windows-2025
    
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
      - uses: illdefined/rust@main
      - run: cargo audit
